FROM cypress/browsers:chrome67

MAINTAINER Christopher Johnson <chjohnson39@gmail.com>
LABEL description = "React Discovery App"
ARG CIRCLE_BRANCH
ENV CIRCLE_BRANCH=${CIRCLE_BRANCH}
WORKDIR /srv/react-discovery
RUN git clone https://github.com/ubl-chj/react-discovery.git ./
RUN git checkout ${CIRCLE_BRANCH}
RUN npm i npm@latest -g
RUN npm install --global lerna
RUN lerna bootstrap --hoist
RUN lerna run build
RUN npx cypress verify
WORKDIR /srv/react-discovery/packages/react-discovery-app
RUN npm install nyc codecov
