export enum SolrParameters {
  CURSOR_MARK = "cursorMark",
  EDISMAX = "edismax",
  FACET = "facet",
  FACET_FIELD = "facet.field",
  FACET_LIMIT = "facet.limit",
  FACET_SORT = "facet.sort",
  FIELD_LIST = "fl",
  FILTER_QUERY = "fq",
  GROUP = "group",
  GROUP_FIELD = "group.field",
  HL = "hl",
  HL_FIELDS = "hl.fl",
  LUCENE = "lucene",
  QF = "qf",
  QUERY = "q",
  QUERY_CONTEXT = '/query',
  ROWS = "rows",
  SORT = "sort",
  START = "start",
  SUGGEST = 'suggest',
  SUGGEST_QUERY = 'suggest.q',
  SUGGEST_BUILD = 'suggest.build',
  SUGGEST_DICTIONARY = 'suggest.dictionary',
  SUGGEST_CONTEXT = '/suggest',
  TYPE_DEF = "defType",
  WT = "wt"
}
